### PR TITLE
Add GNU/Linux example

### PR DESCRIPTION
**Pull request by avtobiff**
- Update example/readme.markdown to include GNU/Linux example.
- Add precompiled syro_volcasample_exsample.x86_64 for x86_64
  architecture, also included "02 Kick 3.wav" sample.
- Add makesyro_gnulinux.sh script, for both interactive and
  non-interactive usage.

### CODE REVIEW

**Comment by Hideki-Fujii** [comment]
Thank you for your work!
Out staff will add file for x86.

**Comment by avtobiff** [comment]
Nice!

**Comment by saitakazuki** [comment]
I found all the binary files generated via Makefile have wrong filename... "syro_volcasample_exsample". Fixed it on master branch.

**Comment by avtobiff** [comment]
Aha, I thought it was a pun with example/sample. :-)

Actually, the other project files reference the exsample name. Also, the
source file is name `korg_syro_volcasample_exsample.c`. So the exsample
name is probably correct.

**Pull request merged**
